{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "mvyzo376xrclzmtc74kg6q2ueu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.4.0.jar",
          "url": "spring-boot-starter-2.4.0.jar",
          "size": 4769,
          "sha512": "0ce7f22e787c05ac12a8be82a53aef53c50661dc20ca407128adeaf3a207926ceef079d59b7208b70c1330295011d87164cd1001e82e17f7809dfaba29b2a918",
          "sha256": "8b8639c92a6d433c09d56ccddf239f5865c0cf5ce7285b5f91777ec579ed19e4",
          "sha1": "26162567b7644e6d245b9d8dcf6fd4efb2bf74f4",
          "md5": "b50c4a14c1d92b9260fbf592ae3b75d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.4.0.jar",
          "url": "spring-boot-starter-2.4.0.jar",
          "size": 4769,
          "sha512": "0ce7f22e787c05ac12a8be82a53aef53c50661dc20ca407128adeaf3a207926ceef079d59b7208b70c1330295011d87164cd1001e82e17f7809dfaba29b2a918",
          "sha256": "8b8639c92a6d433c09d56ccddf239f5865c0cf5ce7285b5f91777ec579ed19e4",
          "sha1": "26162567b7644e6d245b9d8dcf6fd4efb2bf74f4",
          "md5": "b50c4a14c1d92b9260fbf592ae3b75d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.4.0-javadoc.jar",
          "url": "spring-boot-starter-2.4.0-javadoc.jar",
          "size": 4737,
          "sha512": "8bd6ece701eabc3fab280fccaebbb07ca0dd2318f4ed6763b3b66562013744223ae9e4ed4bfb5cec275c8251b1fd46b4715db9987061f953b2257fe93502909b",
          "sha256": "71353a41922a34d256419812af78d2a183e3a573fec197307e96b8b171d72591",
          "sha1": "1b5bb73b770f50bf29838374bfff2d0cadd41027",
          "md5": "c7de956847e46d72687fbe3529f49fce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.4.0-sources.jar",
          "url": "spring-boot-starter-2.4.0-sources.jar",
          "size": 4735,
          "sha512": "bfbed1eaf8182f2dbced69f27ae1a05769baec6fcf799b96e0b5508a5fbc97e910957ff0a69f800bc7708fc62b9f89b84007867138660bf60ec3d0e89eea2e29",
          "sha256": "7c8e7379ae4508463a7e257173a8dd7a061d7316e4ee6b42d12c3da4abbf0781",
          "sha1": "78fc607283c42053ba97019e94a3970b96cab7a7",
          "md5": "c33cd8d2c8622758ffc57ff54408d1c6"
        }
      ]
    }
  ]
}
