{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tge5sx3jtjgf7bjfafercna5sq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xpp3",
              "module": "xpp3_min"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.1.jar",
          "url": "spring-test-5.3.1.jar",
          "size": 751856,
          "sha512": "a341d2f8cb2e43b9c103602341c05c2c7d861d776ff8db3da48a1a0412bb911184952d8a9d97b4ea442fd046dae5a1328f138f36efc95f4ca606856dfefe5f03",
          "sha256": "1b7b6a9454c180e612d1fd6f4130cba47936d745d3aa84dedabff36f2d82d68e",
          "sha1": "ebf8958b28f675897640d1b425a1dbb0bd7c80dd",
          "md5": "d19dde4e09ee5a1332ff69687c783794"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xpp3",
              "module": "xpp3_min"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.1.jar",
          "url": "spring-test-5.3.1.jar",
          "size": 751856,
          "sha512": "a341d2f8cb2e43b9c103602341c05c2c7d861d776ff8db3da48a1a0412bb911184952d8a9d97b4ea442fd046dae5a1328f138f36efc95f4ca606856dfefe5f03",
          "sha256": "1b7b6a9454c180e612d1fd6f4130cba47936d745d3aa84dedabff36f2d82d68e",
          "sha1": "ebf8958b28f675897640d1b425a1dbb0bd7c80dd",
          "md5": "d19dde4e09ee5a1332ff69687c783794"
        }
      ]
    }
  ]
}
