{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tge5sx3jtjgf7bjfafercna5sq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-5.3.1.jar",
          "url": "spring-aop-5.3.1.jar",
          "size": 374303,
          "sha512": "fce43ab40d69c96eeefdbdf278c399e74d253edb30f0eae283afdfb5cad37fc702fa2044aaf8e25ed1a3d5188bab670ca004cbc200239ce4fa13dc902dcb29c7",
          "sha256": "a1f67fe0a11341c7da562053a74457191ead48db8ee49b7713f65c383c8b9526",
          "sha1": "25c310880484082ffba3130deb8e10c5afb29f10",
          "md5": "f08cd6faaf67d097bc4fbdf9684f325c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-5.3.1.jar",
          "url": "spring-aop-5.3.1.jar",
          "size": 374303,
          "sha512": "fce43ab40d69c96eeefdbdf278c399e74d253edb30f0eae283afdfb5cad37fc702fa2044aaf8e25ed1a3d5188bab670ca004cbc200239ce4fa13dc902dcb29c7",
          "sha256": "a1f67fe0a11341c7da562053a74457191ead48db8ee49b7713f65c383c8b9526",
          "sha1": "25c310880484082ffba3130deb8e10c5afb29f10",
          "md5": "f08cd6faaf67d097bc4fbdf9684f325c"
        }
      ]
    }
  ]
}
