{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tge5sx3jtjgf7bjfafercna5sq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.1.jar",
          "url": "spring-web-5.3.1.jar",
          "size": 1546053,
          "sha512": "668d2981042cba75294b91bb684f9a6b5f0de319c928fb4fc85004ace7706d169b40b974945ab86cdb4112017f88d326e8f85160cf2fce65b925f94a6c7308c2",
          "sha256": "925f3b82035f31b410309154c3ae1e48ffa5204280275bdc9390d91312ad4fb4",
          "sha1": "4e1e1d1c6b5a00597162db84132414c409bcf615",
          "md5": "2c074c8766b7fb749bdad2332d61d7f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.1.jar",
          "url": "spring-web-5.3.1.jar",
          "size": 1546053,
          "sha512": "668d2981042cba75294b91bb684f9a6b5f0de319c928fb4fc85004ace7706d169b40b974945ab86cdb4112017f88d326e8f85160cf2fce65b925f94a6c7308c2",
          "sha256": "925f3b82035f31b410309154c3ae1e48ffa5204280275bdc9390d91312ad4fb4",
          "sha1": "4e1e1d1c6b5a00597162db84132414c409bcf615",
          "md5": "2c074c8766b7fb749bdad2332d61d7f5"
        }
      ]
    }
  ]
}
